name: .NET

on:
  push: {}
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        version:
          - "6.0"
          - "7.0"
          - "8.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.version }}.x
      - name: Build
        run: dotnet build --configuration Release --framework net${{ matrix.version }}  /p:TargetFrameworks=net${{ matrix.version }} src/Combination.StringPools.Tests/
      - name: Test
        run: dotnet test --no-build --no-restore --configuration Release --no-restore --framework net${{ matrix.version }} src/Combination.StringPools.Tests/
